version: "2.3"

networks:
  default:
    external:
      name: net_substra

services:
  substra_frontend:
    build:
      context: ./
    container_name: substra-frontend
    hostname: substra-frontend
    ports:
      - "3000:8000"
    restart: unless-stopped
    environment:
      - API_URL=$API_URL
      - NODE_PORT=$NODE_PORT
      - SECURE_NODE_PORT=$SECURE_NODE_PORT
