version: '2.3'

networks:
  default:
    external:
      name: net_substra

services:

  substrafront:
    build:
      context: ./
    container_name: substrafront
    hostname: substrafront
    depends_on:
      - redis
    ports:
      - "3000:8000"
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - FRONT_AUTH_USER=${FRONT_AUTH_USER}
      - FRONT_AUTH_PASSWORD=${FRONT_AUTH_PASSWORD}
      - BACK_AUTH_USER=${BACK_AUTH_USER}
      - BACK_AUTH_PASSWORD=${BACK_AUTH_PASSWORD}
      - API_URL=${API_URL}

  redis:
    container_name: redis
    hostname: redis
    image: redis:4.0.11-alpine
    restart: unless-stopped
